spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
        - id: room-service
          uri: http://localhost:8082/
          predicates:
            - Path=/room/**